### ISSUE TITLE
Write automated tests

### ISSUE THREAD

**Issue by fgmacedo** [rsalmei/clearly#3]
Ideas on how to test?

Tests should include:

- [ ] Tox (multiple Python versions)

**Comment by rsalmei** [comment]
Hey @fgmacedo, I finally found time to work on this 😕 
Anyway, here it is the start of it: https://github.com/rsalmei/clearly/pull/13

I'm thinking about including `tox` too, but only after dropping support for python 2.7, what do you think?
I thought about migrating the project to support 3.5, 3.6 and 3.7, as well as [celery](https://github.com/celery/celery) 3.1, 4.0, 4.1 and 4.2!! That would benefit greatly from `tox`.

Thanks.

**Comment by rsalmei** [comment]
Well, it's done... 👍

**Comment by fgmacedo** [comment]
Congrats!
