### ISSUE TITLE
3.7 Support

### ISSUE THREAD

**Issue by jrabbit** [rsalmei/clearly#34]
I'm working on some polishing of clearly in my fork and noticed errors with 3.7 in the tests?

e.g.

```
___________________________________________________ test_expected_states_task[STARTED-STARTED-expected21] ____________________________________________________

self = <clearly.expected_state.ExpectedStateHandler object at 0x7f5b41078a20>, pre = 'STARTED', post = 'STARTED'

    def states_through(self, pre, post):
        if pre == post:
>           raise StopIteration
E           StopIteration

clearly/expected_state.py:28: StopIteration
```

**Comment by rsalmei** [comment]
Hey @jrabbit, how are you?
Well, that's very odd, I use 3.7 myself in my `Clearly` development...
I'll test again and get back to you.

**Comment by rsalmei** [comment]
Yep, you're right.
My global pyenv is a 3.7, but my local one in `Clearly` dir was a 3.6.
Anyway, I found that [PEP-479](https://www.python.org/dev/peps/pep-0479/) has really changed that Deprecation to an error in python 3.7, thank you.
I'm releasing a new version now, could please validate you can run the tests now @jrabbit?

**Comment by rsalmei** [comment]
Well, I'm closing this one, as this bug has long gone.
