### ISSUE TITLE
Got this Attribute Error

### ISSUE THREAD

**Issue by bobozar** [rsalmei/clearly#56]
Hello,

I can't get to start the clearly server on ubuntu 16.04 /python 3.6.8. I got this error:

```
 from google.protobuf import symbol_database as _symbol_database
  File "/var/www/deddd/lib/python3.6/site-packages/google/protobuf/symbol_database.py", line 193, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: module 'google.protobuf.descriptor_pool' has no attribute 'Default'
```

I used this command to start the server:

`clearly server amqp://localhost`

**Comment by rsalmei** [comment]
Hey @bobozar 

That's odd, it seems to be a new version of google's protobuf.
Please post the output of your `pip list`, in the same virtual env you installed `clearly`.

**Comment by bobozar** [comment]
Package                   Version
------------------------- -----------
about-time                3.0.0
amqp                      2.5.0
apns2                     0.5.0
arrow                     0.14.2
asn1crypto                0.24.0
Babel                     2.7.0
backcall                  0.1.0
backports.csv             1.0.7
basho-erlastic            2.1.1
billiard                  3.6.0.0
boto3                     1.9.187
botocore                  1.12.187
cairocffi                 1.0.2
CairoSVG                  2.4.1
cassandra-driver          3.23.0
celery                    4.3.0
certifi                   2019.6.16
cffi                      1.12.3
chardet                   3.0.4
clearly                   0.9.2
click                     7.1.2
cryptography              2.7
cssselect2                0.2.1
DateTime                  4.3
decorator                 4.4.2
defusedxml                0.6.0
diff-match-patch          20181111
Django                    2.2.3
django-celery-beat        1.5.0
django-celery-results     1.1.2
django-cors-headers       3.0.2
dnspython                 1.16.0
docutils                  0.14
elasticsearch             7.7.0
enum34                    1.1.6
et-xmlfile                1.0.1
eventlet                  0.25.0
flower                    0.9.3
future                    0.18.2
fuzzywuzzy                0.17.0
geoip2                    2.9.0
geomet                    0.1.2
greenlet                  0.4.15
grpcio                    1.28.1
gunicorn                  19.9.0
h2                        2.6.2
hpack                     3.0.0
html5lib                  1.0.1
http-ece                  1.1.0
hyper                     0.7.0
hyperframe                3.2.0
idna                      2.8
ipython                   7.14.0
ipython-genutils          0.2.0
jdcal                     1.4.1
jedi                      0.17.0
jmespath                  0.9.4
jsonfield                 2.0.2
kombu                     4.6.3
Markdown                  3.1.1
maxminddb                 1.5.1
monotonic                 1.5
mysqlclient               1.4.2.post1
ndg-httpsclient           0.5.1
numpy                     1.16.4
odfpy                     1.4.0
onesignal-sdk             1.1.0
openpyxl                  2.6.3
pandas                    0.25.3
parso                     0.7.0
pdfkit                    0.6.1
pdfrw                     0.4
pexpect                   4.8.0
phonenumbers              8.10.14
pickleshare               0.7.5
Pillow                    6.1.0
pip                       19.1.1
prompt-toolkit            3.0.5
protobuf                  3.11.3
ptyprocess                0.6.0
py-vapid                  1.7.0
pyArango                  1.3.4
pyasn1                    0.4.5
pycparser                 2.19
Pygments                  2.6.1
PyJWT                     1.7.1
pyOpenSSL                 19.0.0
pyotp                     2.3.0
PyPDF2                    1.26.0
Pyphen                    0.9.5
PySocks                   1.7.0
python-consul             1.1.0
python-crontab            2.3.8
python-dateutil           2.8.0
python-Levenshtein        0.12.0
python-memcached          1.59
python3-protobuf          2.5.0
pytz                      2019.1
pywebpush                 1.9.4
PyYAML                    5.1.2
range-key-dict            1.1.0
redis                     3.5.1
reportlab                 3.5.23
requests                  2.22.0
riak                      2.7.0
s3transfer                0.2.1
setuptools                41.0.1
six                       1.12.0
SQLAlchemy                1.3.17
sqlparse                  0.3.0
tablib                    0.13.0
tinycss2                  1.0.2
tornado                   5.1.1
traitlets                 4.3.3
twilio                    6.29.1
ua-parser                 0.8.0
urllib3                   1.25.3
user-agents               2.0
vine                      1.3.0
wcwidth                   0.1.9
webencodings              0.5.1
wheel                     0.33.4
xhtml2pdf                 0.2.3
xlrd                      1.2.0
xlwt                      1.3.0
zope.interface            5.1.0

**Comment by rsalmei** [comment]
It seems several people had this problem, a search of that error got me a bunch of results.
I suggest you see this thread, particularly the last comment: https://github.com/protocolbuffers/protobuf/issues/2350
I think your system may be finding two versions of that same protobuf package.
Let me know what you find.

**Comment by rsalmei** [comment]
Oh, you could also try the docker image, which is isolated from your system and also the recommended way to use `clearly` nowadays.

**Comment by bobozar** [comment]
I will look into it later tonight. 

Also, I'm not using docker. :(

**Comment by bobozar** [comment]
I managed to clear the error by first uninstalling the package and run this:

`pip install protobuf==3.0.0b2`

After that, I did, 

`pip install --upgrade protobuf`

Now, it's working but yet to show any task result.

**Comment by rsalmei** [comment]
Please start the server with `clearly server --debug amqp://localhost`.
Then you'll be able to see if the client successfully connect, just to baby steps.
Would you post the server log on screen?

**Comment by rsalmei** [comment]
Ok, please open a new issue if you need.
