### ISSUE TITLE
Support custom Event exchange / multiple exchanges

### ISSUE THREAD

**Issue by tjader** [rsalmei/clearly#57]
Hi, We are using a custom named event queue (set by the event_exchange option in celery), but from what I can see, there is no way of configuring event_exchange in clearly at this point. Can you support configuring the event_exchange?

Also, we have multiple subapplication, and we are considering splitting event exchange on a per-subapplication basis. Would it be possible to support multiple event exchanges in clearly (so that we only need one cleary instance?

Thank you,

**Comment by rsalmei** [comment]
Hello @tjader 

Out of curiosity, why would you change the exchange used by the events subsystem? It is not standard to change this, only the one used by the task queues (https://docs.celeryproject.org/en/latest/userguide/configuration.html?highlight=exchange#message-routing).

I think I could support that, but I'm pretty sure there's hardly any demand for that.
Even celery itself recommends against it:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/6652853/82830396-fff35000-9e8b-11ea-8451-9a2322a42f04.png">

Couldn't you reconsider that?

**Comment by rsalmei** [comment]
Regarding the multiple subapplications, if you're are really using the very same RabbitMQ instance for more than one application, I'd recommend to use different virtual-hosts, and leave the default event exchange in all of them.

**Comment by tjader** [comment]
Thanks @rsalmei , I'll give it a think.
